// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycbirinitkhixwlwywho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljYmlyaW5pdGtoaXh3bHd5d2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTM2MzQsImV4cCI6MjA2NzEyOTYzNH0.ClW7kVgl3gbmEII9vQP5T_ZLjmuNrllmlLxQ_YI6h7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});